#!/usr/bin/env bash
set -uo pipefail
BASE=http://localhost:8080
PASS=0
FAIL=0
record(){ local name="$1" status="$2" detail="$3"; if [ "$status" = PASS ]; then PASS=$((PASS+1)); else FAIL=$((FAIL+1)); fi; echo "[$status] $name"; echo "  $detail"; }
http_code(){ curl -s -o "$1" -w "%{http_code}" "${@:2}"; }
TMP=$(mktemp)
post_json(){ http_code "$TMP" -X POST "$BASE/logs" -H "Content-Type: application/json" -d "$1"; }
get_url(){ http_code "$TMP" "$1"; }
echo "========== POST /logs =========="
code=$(post_json '{"logs":[{"timestamp":"2026-07-20T14:32:01.123Z","level":"error","service":"checkout","message":"payment declined","attributes":{"user_id":"42"}}]}'); body=$(cat "$TMP"); [ "$code" = 200 ] && echo "$body" | grep -q '"accepted":1' && record "POST single valid" PASS "code=$code body=$body" || record "POST single valid" FAIL "code=$code body=$body"
code=$(post_json '{"logs":[{"timestamp":"2026-07-20T14:32:01.123Z","level":"info","service":"a","message":"m1"},{"timestamp":"2026-07-20T14:32:02.123Z","level":"warn","service":"b","message":"m2"}]}'); body=$(cat "$TMP"); [ "$code" = 200 ] && echo "$body" | grep -q '"accepted":2' && record "POST multiple valid" PASS "code=$code body=$body" || record "POST multiple valid" FAIL "code=$code body=$body"
code=$(post_json '{"logs":[{"timestamp":"2026-07-20T14:32:01.123Z","level":"info","service":"mix","message":"ok"},{"timestamp":"bad","level":"info","service":"mix","message":"bad ts"}]}'); body=$(cat "$TMP"); [ "$code" = 200 ] && echo "$body" | grep -q '"accepted":1' && echo "$body" | grep -q rejected && record "POST mixed valid/invalid" PASS "code=$code body=$body" || record "POST mixed valid/invalid" FAIL "code=$code body=$body"
code=$(post_json '{"logs":[{"timestamp":"2026-07-20T14:32:01.123Z","level":"critical","service":"x","message":"y"}]}'); body=$(cat "$TMP"); [ "$code" = 400 ] && record "POST all-invalid batch" PASS "code=$code body=$body" || record "POST all-invalid batch" FAIL "code=$code body=$body"
code=$(curl -s -o "$TMP" -w "%{http_code}" -X POST "$BASE/logs" -H "Content-Type: application/json" -d '{not json'); body=$(cat "$TMP"); [ "$code" = 400 ] && echo "$body" | grep -qi error && record "POST malformed JSON" PASS "code=$code body=$body" || record "POST malformed JSON" FAIL "code=$code body=$body"
code=$(post_json '{"notlogs":[]}'); body=$(cat "$TMP"); [ "$code" = 400 ] && record "POST missing logs array" PASS "code=$code body=$body" || record "POST missing logs array" FAIL "code=$code body=$body"
FUTURE=$(date -u -d "+10 minutes" +%Y-%m-%dT%H:%M:%S.000Z 2>/dev/null || python3 -c "from datetime import datetime,timedelta,timezone; print((datetime.now(timezone.utc)+timedelta(minutes=10)).strftime('%Y-%m-%dT%H:%M:%S.000Z'))")
code=$(post_json "{\"logs\":[{\"timestamp\":\"$FUTURE\",\"level\":\"info\",\"service\":\"f\",\"message\":\"future\"}]}"); body=$(cat "$TMP"); [ "$code" = 400 ] && record "POST future timestamp" PASS "code=$code body=$body" || record "POST future timestamp" FAIL "code=$code body=$body"
code=$(post_json '{"logs":[{"timestamp":"2026-07-20T14:32:01.123Z","level":"trace","service":"s","message":"m"}]}'); b1=$(cat "$TMP"); c1=$code
code=$(post_json '{"logs":[{"timestamp":"2026-07-20T14:32:01.123Z","level":"info","service":"","message":"m"}]}'); b2=$(cat "$TMP"); c2=$code
code=$(post_json '{"logs":[{"timestamp":"2026-07-20T14:32:01.123Z","level":"info","service":"s","message":""}]}'); b3=$(cat "$TMP"); c3=$code
[ "$c1" = 400 ] && [ "$c2" = 400 ] && [ "$c3" = 400 ] && record "POST invalid level/empty service/message" PASS "c1=$c1 c2=$c2 c3=$c3" || record "POST invalid level/empty service/message" FAIL "$b1 | $b2 | $b3"
code=$(post_json '{"logs":[{"timestamp":"2026-07-20T14:32:01.123Z","level":"info","service":"attr","message":"nested","attributes":{"nested":{"a":1}}},{"timestamp":"2026-07-20T14:32:01.123Z","level":"info","service":"attr","message":"array","attributes":{"arr":[1]}}]}'); body=$(cat "$TMP"); [ "$code" = 400 ] && record "POST nested/array attributes" PASS "code=$code body=$body" || record "POST nested/array attributes" FAIL "code=$code body=$body"
code=$(post_json '{"logs":[{"timestamp":"2026-07-20T14:32:01.123Z","level":"info","service":"attr","message":"types","attributes":{"s":"str","n":42,"b":true}}]}'); body=$(cat "$TMP"); [ "$code" = 200 ] && echo "$body" | grep -q '"accepted":1' && record "POST string/number/boolean attrs" PASS "code=$code body=$body" || record "POST string/number/boolean attrs" FAIL "code=$code body=$body"
echo "========== Seed query data =========="
python3 -c "import json,urllib.request; logs=[{'timestamp':'2026-08-01T10:00:00.000Z','level':'info' if i%2==0 else 'error','service':'paginate-svc' if i<200 else 'filter-svc','message':f'declined payment {i}','attributes':{'user_id':str(i%5),'idx':i}} for i in range(250)]+[{'timestamp':'2026-08-01T10:00:00.001Z','level':'info','service':'order-svc','message':f'dup-ts {i}','attributes':{'seq':i}} for i in range(5)]; body=json.dumps({'logs':logs}).encode(); req=urllib.request.Request('http://localhost:8080/logs',data=body,headers={'Content-Type':'application/json'},method='POST'); print(urllib.request.urlopen(req).read().decode())"
echo "========== GET /logs =========="
code=$(get_url "$BASE/logs?service=filter-svc&limit=10"); [ "$code" = 200 ] && record "GET service filter" PASS "code=$code $(cat $TMP|head -c120)" || record "GET service filter" FAIL "code=$code"
code=$(get_url "$BASE/logs?level=error&service=paginate-svc&limit=5"); [ "$code" = 200 ] && record "GET level filter" PASS "code=$code" || record "GET level filter" FAIL "code=$code"
code=$(get_url "$BASE/logs?since=2026-08-01T10:00:00.000Z&until=2026-08-01T11:00:00.000Z&service=paginate-svc&limit=5"); [ "$code" = 200 ] && record "GET since/until" PASS "code=$code" || record "GET since/until" FAIL "code=$code"
code=$(get_url "$BASE/logs?attr.user_id=2&service=paginate-svc&limit=20"); [ "$code" = 200 ] && record "GET attr filter" PASS "code=$code" || record "GET attr filter" FAIL "code=$code"
code=$(get_url "$BASE/logs?q=declined&service=paginate-svc&limit=5"); [ "$code" = 200 ] && record "GET q search" PASS "code=$code" || record "GET q search" FAIL "code=$code"
code=$(get_url "$BASE/logs?service=paginate-svc&limit=9999"); n=$(python3 -c "import json; print(len(json.load(open('$TMP'))['logs']))"); [ "$code" = 200 ] && [ "$n" -le 1000 ] && record "GET limit max" PASS "returned=$n" || record "GET limit max" FAIL "code=$code n=$n"
code=$(get_url "$BASE/logs?service=paginate-svc"); n=$(python3 -c "import json; print(len(json.load(open('$TMP'))['logs']))"); [ "$code" = 200 ] && [ "$n" -le 101 ] && record "GET limit default" PASS "returned=$n" || record "GET limit default" FAIL "returned=$n code=$code"
code=$(get_url "$BASE/logs?limit=abc"); [ "$code" = 400 ] && record "GET invalid limit" PASS "$(cat $TMP)" || record "GET invalid limit" FAIL "code=$code"
code=$(get_url "$BASE/logs?since=2026-08-01T12:00:00.000Z&until=2026-08-01T10:00:00.000Z"); [ "$code" = 400 ] && record "GET until < since" PASS "$(cat $TMP)" || record "GET until < since" FAIL "code=$code"
ids=""; cursor=""; pages=0; dup=0; last_code=0
while [ $pages -lt 20 ]; do url="$BASE/logs?service=paginate-svc&limit=50"; [ -n "$cursor" ] && url="$url&cursor=$cursor"; last_code=$(get_url "$url"); [ "$last_code" != 200 ] && break; page_ids=$(python3 -c "import json; d=json.load(open('$TMP')); print(' '.join(x['id'] for x in d['logs']))"); for id in $page_ids; do echo " $ids " | grep -q " $id " && dup=1; ids="$ids $id"; done; cursor=$(python3 -c "import json; print(json.load(open('$TMP')).get('next_cursor') or '')"); pages=$((pages+1)); [ -z "$cursor" ] && break; done
total=$(echo $ids | wc -w); [ "$last_code" = 200 ] && [ "$dup" -eq 0 ] && [ "$total" -ge 200 ] && record "GET cursor pagination" PASS "pages=$pages total=$total" || record "GET cursor pagination" FAIL "pages=$pages total=$total dup=$dup code=$last_code"
code=$(get_url "$BASE/logs?service=order-svc&since=2026-08-01T10:00:00.000Z&until=2026-08-01T10:00:01.000Z&limit=10"); order=$(python3 -c "import json; d=json.load(open('$TMP')); print([(x['timestamp'],x.get('attributes',{}).get('seq')) for x in d['logs']])"); [ "$code" = 200 ] && record "GET same-ts order" PASS "$order" || record "GET same-ts order" FAIL "code=$code"
ts_check=$(python3 -c "import json,urllib.request; d=json.loads(urllib.request.urlopen('http://localhost:8080/logs?service=paginate-svc&limit=20').read()); ts=[x['timestamp'] for x in d['logs']]; print('PASS' if all(ts[i]>=ts[i+1] for i in range(len(ts)-1)) else 'FAIL')"); echo "$ts_check" | grep -q PASS && record "GET descending timestamp" PASS "$ts_check" || record "GET descending timestamp" FAIL "$ts_check"
echo "========== GET /logs/aggregate =========="
for b in 1m 5m 1h 1d; do code=$(get_url "$BASE/logs/aggregate?since=2026-08-01T10:00:00.000Z&until=2026-08-01T12:00:00.000Z&bucket=$b&service=paginate-svc"); [ "$code" = 200 ] && record "GET aggregate bucket=$b" PASS "code=$code" || record "GET aggregate bucket=$b" FAIL "code=$code $(cat $TMP)"; done
code=$(get_url "$BASE/logs/aggregate?since=2026-08-01T10:00:00.000Z&until=2026-08-01T12:00:00.000Z&bucket=1m&group_by=service"); [ "$code" = 200 ] && record "GET aggregate group_by=service" PASS "$(cat $TMP|head -c200)" || record "GET aggregate group_by=service" FAIL "code=$code"
code=$(get_url "$BASE/logs/aggregate?since=2026-08-01T10:00:00.000Z&until=2026-08-01T12:00:00.000Z&bucket=1m&group_by=level"); [ "$code" = 200 ] && record "GET aggregate group_by=level" PASS "code=$code" || record "GET aggregate group_by=level" FAIL "code=$code"
code=$(get_url "$BASE/logs/aggregate?since=2026-08-01T10:00:00.000Z&until=2026-08-01T12:00:00.000Z&bucket=1m"); null_ok=$(python3 -c "import json; bs=json.load(open('$TMP'))['buckets']; print(all(x.get('group') is None for x in bs))"); [ "$code" = 200 ] && [ "$null_ok" = True ] && record "GET aggregate no group_by" PASS "code=$code" || record "GET aggregate no group_by" FAIL "code=$code null_ok=$null_ok"
code=$(get_url "$BASE/logs/aggregate?since=bad&until=2026-08-01T12:00:00.000Z&bucket=1m"); [ "$code" = 400 ] && record "GET aggregate invalid params" PASS "$(cat $TMP)" || record "GET aggregate invalid params" FAIL "code=$code"
echo "========== SUMMARY =========="; echo "PASS=$PASS FAIL=$FAIL TOTAL=$((PASS+FAIL))"
